// Generated automatically from ..\Documents\projects\wray\src\api.wren. Do not edit.
static const char* apiModuleSource =
"class Window {\n"
"    foreign static init(width, height, title)\n"
"    foreign static close()\n"
"\n"
"    foreign static closed\n"
"    foreign static width\n"
"    foreign static height\n"
"    foreign static fps\n"
"    foreign static targetFps=(fps)\n"
"}\n"
"\n"
"class Graphics {\n"
"    foreign static begin()\n"
"    foreign static end()\n"
"    foreign static clear(color)\n"
"    foreign static rect(x, y, width, height, color)\n"
"    foreign static text(text, x, y, size, color)\n"
"}\n"
"\n"
"class Mouse {\n"
"    foreign static pressed(button)\n"
"    foreign static down(button)\n"
"\n"
"    foreign static x\n"
"    foreign static y\n"
"}\n"
"\n"
"foreign class Color {\n"
"    foreign construct new(r, g, b, a)\n"
"    foreign construct new(r, g, b)\n"
"\n"
"    foreign [index]\n"
"    foreign [index]=(v)\n"
"\n"
"    r { this[0] }\n"
"    g { this[1] }\n"
"    b { this[2] }\n"
"    a { this[3] }\n"
"\n"
"    r=(v) { this[0] = v }\n"
"    g=(v) { this[0] = v }\n"
"    b=(v) { this[0] = v }\n"
"    a=(v) { this[0] = v }\n"
"\n"
"    toString { \"Color (r: %(r), g: %(g), b: %(b), a: %(a))\" }\n"
"\n"
"    static none { new(0, 0, 0, 0) }\n"
"    static black { new(0, 0, 0) }\n"
"    static darkBlue { new(29, 43, 83) }\n"
"    static darkPurple { new(126, 37, 83) }\n"
"    static darkGreen { new(0, 135, 81) }\n"
"    static brown { new(171, 82, 54) }\n"
"    static darkGray { new(95, 87, 79) }\n"
"    static lightGray { new(194, 195, 199) }\n"
"    static white { new(255, 241, 232) }\n"
"    static red { new(255, 0, 77) }\n"
"    static orange { new(255, 163, 0) }\n"
"    static yellow { new(255, 236, 39) }\n"
"    static green { new(0, 228, 54) }\n"
"    static blue { new(41, 173, 255) }\n"
"    static indigo { new(131, 118, 156) }\n"
"    static pink { new(255, 119, 168) }\n"
"    static peach { new(255, 204, 170) }\n"
"}\n"
"\n"
"foreign class Texture {\n"
"    foreign construct new(path)\n"
"\n"
"    foreign draw(x, y, color)\n"
"\n"
"    foreign width\n"
"    foreign height\n"
"}\n";
